### ISSUE TITLE
AssemblyInfo.cs missing

### ISSUE THREAD

**Issue by elmorena** [mzajkowski/umbraco-rest-api-playground#1]
I get the following error in Visual Studio 2015

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'D:\OneDrive\web\umbraco-rest-api-playground-master\RestApiPlayground\TestSite\Properties\AssemblyInfo.cs' could not be found.	TestSite	D:\OneDrive\web\umbraco-rest-api-playground-master\RestApiPlayground\TestSite\CSC	1	Active

**Comment by mzajkowski** [comment]
Thanks @elmorena for reporting this. File was missing! I've included default assembly file and solution is now working. Feel free to play with it after grabbing the latest version of code.
