### ISSUE TITLE
http://localhost:55368/hal-browser/ just gives a Http error 403 - Forbidden

### ISSUE THREAD

**Issue by Joniff** [mzajkowski/umbraco-rest-api-playground#2]
Hey Marcin,

My install steps.

1. Download zip of this project
2. Copied zip contents to folder on my hard drive
3. Opened the solution, realised that I hadn't given the right file permissions to the files.
4. Closed the solution, Gave my user, full file access to the files
5. Re-opened the solution
6. Built the solution - Everything Good
7. Pressed F5 to run solution
8. Home page of Fanoe appeared, **Looking good**
9. Change url to [http://localhost:55368/umbraco](http://localhost:55368/umbraco) and logged in with admin/password. See content tree, everything looks normal.
10. Surf to [http://localhost:55368/hal-browser/](http://localhost:55368/hal-browser/) and get HTTP error
![image](https://cloud.githubusercontent.com/assets/12765209/25612979/996f381e-2f24-11e7-8914-5189b8c6aec6.png)

Any advice. To make clear I really don't understand this Hal browser which is why I was taking a look at your project to see how to use. I mean, I see code, but I don't know how to host 'it' in Umbraco - to be honest, the only reason I want it, is to see what it does as people keep saying to use it with Umbraco Rest API and I'm guessing it does something more than just HTTP error 403.

Cheers

Jonathan

**Comment by mzajkowski** [comment]
Hi Jonathan,

can you ensure you have '~/hal-browser' in the value of umbracoReservedPaths (in your web.config) and the content of the hal-browser directory is on place?

<add key="umbracoReservedPaths" value="~/umbraco,~/install/,~/hal-browser/" />

**Comment by Joniff** [comment]
Thanks for replying Marcin, much appreciated.

I've just doubled checked, and yeah, as my code is literal a copy of this repository and luckily NuGet hasn't overwritten my Umbraco config files when I compiled, I do have that line in my web.config

[<add key="umbracoReservedPaths" value="~/umbraco,~/install/,~/hal-browser/"/>](https://github.com/mzajkowski/umbraco-rest-api-playground/blob/master/RestApiPlayground/TestSite/Web.config#L40)

and yeah the /hal-browser/ folder also exists in the web root.

I'm guessing from your answers that [http://localhost:55368/hal-browser/](http://localhost:55368/hal-browser/) has no special routing, eg a controller or anything and you are expecting IIS Express to just serve up that folder 'as is' - but there is no html file in that folder, which noticing other peoples implementation of hal-browser they do have an browser.html & login.html in their /hal-browser/ folder

Cheers for this, you have helped hugely.

Jonathan

**Comment by mzajkowski** [comment]
Arghh... _.gitignore_ from hal-browser was ignoring all the html files. Removed it and updated hal-browser. 

Good one! So now browser is visible at http://localhost:55368/hal-browser/browser.html.
